### ISSUE TITLE
getUser test fails on language/country

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar-js#11]
Country and language don't match in the `getUser` by id test:

```
  1) NorthstarClient unauthorized getUser() by id should return correct Northstar user:
     AssertionError: expected NorthstarUser {
  country: null,
  createdAt: '2014-03-14T15:05:57+0000',
  drupalID: '187',
  firstName: 'test',
  id: '5480c950bffebc651c8b456f',
  isAuthorized: false,
  language: '',
  lastInitial: 'L',
  photo: 'https://avatar.dosomething.org/uploads/avatars/5480c950bffebc651c8b456f.jpeg',
  updatedAt: '2016-08-09T19:08:23+0000'
} to match Function { name: 'unauthorizedTestUser' }
    expected NorthstarUser {
      country: null,
      createdAt: '2014-03-14T15:05:57+0000',
      drupalID: '187',
      firstName: 'test',
      id: '5480c950bffebc651c8b456f',
      isAuthorized: false,
      language: '',
      lastInitial: 'L',
      photo: 'https://avatar.dosomething.org/uploads/avatars/5480c950bffebc651c8b456f.jpeg',
      updatedAt: '2016-08-09T19:08:23+0000'
    } to have properties language of 'en-global' (got ''), country of 'US' (got null)
      at Assertion.fail (node_modules/should/lib/assertion.js:92:17)
      at Assertion.Object.defineProperty.value [as match] (node_modules/should/lib/assertion.js:164:19)
      at node_modules/should/lib/assertion.js:193:24
```

**Comment by aaronschachter** [comment]
Ran our `testUserBy('email', 'test@dosomething.org');` query with cURL and confirmed that indeed we get back a null for `country` and empty string for `language`:

```
curl -X GET   -H "X-DS-REST-API-Key: [removed]"   -H "Content-Type: application/json"   -H "Accept: application/json"    https://northstar-qa.dosomething.org/v1/users/email/test@dosomething.org
{"data":{"id":"5480c950bffebc651c8b456f","_id":"5480c950bffebc651c8b456f","first_name":"test","last_name":"Last","last_initial":"L","photo":"https://avatar.dosomething.org/uploads/avatars/5480c950bffebc651c8b456f.jpeg","email":"test@dosomething.org","mobile":"5555555555","facebook_id":null,"interests":["interest number 1","int num 2"],"birthdate":"1989-04-05 00:00:00","addr_street1":"123","addr_street2":"456","addr_city":"Paris","addr_state":"Florida","addr_zip":"555555","source":"phoenix","mobilecommons_id":null,"parse_installation_ids":["parse-test"],"mobilecommons_status":null,"language":"","country":null,"drupal_id":"187","role":"user","updated_at":"2016-08-09T19:08:23+0000","created_at":"2014-03-14T15:05:57+0000"}}
```

**Comment by aaronschachter** [comment]
Hey @sergii-tkachenko -- I was asking @DFurnes about this in our #api slack room today when looking to get setup with a Northstar key to use for the Gambit repo:

>  I imagine that user had different profile values when Sergii wrote the tests. We shouldn’t really be running tests against an external data set (for that reason, and so we can run tests as part of an automated Wercker/Travis/etc build).

Any suggestions for refactoring this test to avoid failure? One idea could be to simply check for the property we're searching by and disregarding all other properties (e.g. `country`, `language`)

**Comment by sergiitk** [comment]
Ah. I meant we just need to update test values to the current ones.

**Comment by DFurnes** [comment]
Having the test suite rely on production data is going to be inherently fragile – especially because that `test@dosomething.org` account is often used for manual testing.

We do have some more "hidden" test accounts for Runscope monitoring that are _less_ likely to randomly change, but I still think the best approach here would be to completely mock the HTTP requests using something like [Sinon](http://sinonjs.org) or [testdouble.js](https://github.com/testdouble/testdouble.js). Ideally, we should only be testing interactions _between_ layers of our stack for high level monitoring or integration tests.

**Comment by sergiitk** [comment]
Can we just use hidden test accounts for now?

**Comment by DFurnes** [comment]
Haha obviously we _can_. Just trying to help provide some more context for why I've said this isn't how I'd recommend doing things. Feel free to disregard. 😉

**Comment by sergiitk** [comment]
I agree that we should end up mocking HTTP at some point. It's just now I feel like this it too much for the task. Thank you very much for the suggestions!
