### ISSUE TITLE
Remove /users namespace from DS_REST_API_BASEURI

### ISSUE THREAD

**Issue by aaronschachter** [DoSomething/northstar-js#12]
Refs https://github.com/DoSomething/northstar-js/blob/a8d5db21b9735d351a39a16733e8c84e33baf06b/README.md#testing

```
DS_REST_API_BASEURI=https://northstar-qa.dosomething.org/v1/users
```

Looking to add support for Signups and Reportbacks in https://github.com/dosomething/gambit/issues/606, so we'll want to refactor to add the `/users/` to URL from within [`getUser`](https://github.com/DoSomething/northstar-js/blob/a8d5db21b9735d351a39a16733e8c84e33baf06b/lib/northstar-client.js#L36)

**Comment by sergiitk** [comment]
Makes sense.
Also, there's another one library built in very similar way: https://github.com/DoSomething/phoenix-js/tree/master/lib

I implemented something very similar there.

**Comment by sergiitk** [comment]
I separated different namespaces to own "endpoint" classes: https://github.com/DoSomething/phoenix-js/blob/master/lib/phoenix-endpoint-user.js#L17
